---
- name: Install apps
  hosts: localhost
  tasks:
    - name: Terminal tools setup
      ansible.builtin.import_role:
        name: terminal
    - name: Clipboard manager setup
      ansible.builtin.import_role:
        name: gpaste
    - name: Docker image inspection tool setup
      ansible.builtin.import_role:
        name: docker_dive
    - name: K8s tooling setup
      ansible.builtin.import_role:
        name: k8s
    - name: Disk tools setup
      ansible.builtin.import_role:
        name: disk_tools
